services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - promtail
    networks:
      - web-net2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
#    environment:
#      - GF_PATHS_CONFIG=/etc/grafana/provisioning/grafana.ini
#      - GF_INSTALL_PLUGINS=
#    command: "--config=/etc/grafana/provisioning/grafana.ini"
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - grafana:/var/lib/grafana
    networks:
      - web-net2

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
#      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
#      - /sys:/sys:ro
#      - /Users/$LOGNAME/.docker/run/docker.sock:/var/run/docker.sock
#      - /var/lib/docker:/var/lib/docker:rw
#      - /dev/disk:/dev/disk:ro
    networks:
      - web-net2

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - --path.rootfs=/host
    restart: unless-stopped
    ports:
      - 9110:9100
    volumes:
     - /:/host:ro
    networks:
      - web-net2

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      -  3100:3100
    depends_on:
      - promtail
    networks:
      - web-net2

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command:
      - -config.file=/etc/promtail/promtail.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config/promtail.yml:/etc/promtail/promtail.yml:ro
      - /tmp:/tmp
    networks:
      - web-net2

volumes:
  grafana:
networks:
  web-net2:
