services:
  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 7777:80
    volumes:
      - wordpress:/var/www/html
#      - ./.wp:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web-net
      - web-net2

  wordpress:
#    image: wordpress:latest
    depends_on:
      - database
      - redis
    build: ./wp
    ports:
      - 80
#      - 8080:80
#    image: wordpress:6.7.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=database:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
#      - WP_REDIS_HOST=redis
#      - WP_REDIS_PORT=6379
    volumes:
#      - ./.wp:/var/www/html    
      - wordpress:/var/www/html
    networks:
      - web-net
      - app-network

  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  redis:
    image: redis:8.0-M02-alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - app-network

volumes:
  wordpress:
  dbdata:

networks:
  web-net:
  web-net2:
  app-network:
 
